### ISSUE TITLE
### without a preceding newline prevents compiling

### ISSUE THREAD

**Issue by elsamannila** [k7hoven/spexcript#1]
Addding the line 
`<A test example ### sdf` 
causes an otherwise compiling input file to make the program hang, adding a newline helps.

**Comment by k7hoven** [comment]
Another issue in the new handling of special characters. Needs fixing.

**Comment by k7hoven** [comment]
Old syntax allowed a new section starting anywhere in a line. That's not allowed anymore, which caused the hashes to leak through and cause problems. Should be fine in next release.
